-- Supprime les tables s'il elles existent déjà
DROP TABLE IF EXISTS masters, academies, communes, regions;

-- Table pour les masters
CREATE TABLE masters(
    id_etablissement INTEGER NOT NULL, -- Identifiant de l'établissement (clé primaire)
    type_etablissement VARCHAR(20), -- Type d'établissement
    etablissement VARCHAR(100), -- Nom de l'établissement
    type_diplome VARCHAR(50), -- Type de diplôme
    regroupement_diplomes VARCHAR(50), -- Regroupement des diplômes
    libelle_diplome VARCHAR(100), -- Libellé du diplôme
    grande_discipline VARCHAR(50), -- Grande discipline
    secteur_disciplinaire VARCHAR(50), -- Secteur disciplinaire
    nb_etudiants INTEGER, -- Nombre total d'étudiants
    nb_femmes INTEGER, -- Nombre de femmes
    nb_hommes INTEGER, -- Nombre d'hommes
    code_commune  VARCHAR(50), -- Code de la commune
    commune VARCHAR(50), -- Nom de la commune
    departement VARCHAR(50), -- Département
    id_academie VARCHAR(50), -- Identifiant de l'académie
    académie VARCHAR(50), -- Nom de l'académie
    id_region VARCHAR(50), -- Identifiant de la région
    region VARCHAR(50), -- Nom de la région
    CodeUAI VARCHAR(50), -- Code UAI
    etablissement_actuel VARCHAR(100), -- Nom de l'établissement actuel
    PRIMARY KEY (id_etablissement) -- Clé primaire
);

-- Table pour les académies
CREATE TABLE academies(
    id_academie VARCHAR(5) NOT NULL, -- Identifiant de l'académie (clé primaire)
    academie VARCHAR(50), -- Nom de l'académie
    PRIMARY KEY(id_academie) -- Clé primaire
);

-- Table pour les communes
CREATE TABLE communes(
    id_commune VARCHAR(5) NOT NULL, -- Identifiant de la commune (clé primaire)
    commune VARCHAR(50), -- Nom de la commune
    PRIMARY KEY(id_commune) -- Clé primaire
);

-- Table pour les régions
CREATE TABLE regions(
    id_region VARCHAR(5) NOT NULL, -- Identifiant de la région (clé primaire)
    region VARCHAR(50), -- Nom de la région
    PRIMARY KEY(id_region) -- Clé primaire
);

INSERT INTO masters VALUES (1,'Université','Université Paris-Saclay','Diplômes nationaux','Autres formations','INFORMATIQUE','Sciences et sciences de lingénieur','Informatique',1,0,1,'91471','Orsay','Essonne','A25','Versailles','R11','Île-de-France','0912408Y','Université Paris-Saclay');
INSERT INTO masters VALUES (2,'Université','CY Cergy Paris Université','Diplômes nationaux','Master','INFORMATIQUE ET INGENIERIE DES SYSTEMES COMPLEXES','Sciences et sciences de lingénieur','Informatique',0,0,0,'95127','Cergy','Val-dOise','A25','Versailles','R11','Île-de-France','0952259P','CY Cergy Paris Université');
INSERT INTO masters VALUES (3,'Université','Université Jean Moulin - Lyon 3','Diplômes nationaux','Master','AUDIOVISUEL, MEDIAS INTERACTIFS NUMERIQUES, JEUX','Sciences et sciences de lingénieur','Informatique',14,8,6,'69387','Lyon 7e','Rhône','A10','Lyon','R84','Auvergne-Rhône-Alpes','0692437Z','Université Jean Moulin - Lyon 3');
INSERT INTO masters VALUES (4,'Université','Université de Poitiers','Diplômes nationaux','Master','AUDIOVISUEL, MEDIAS INTERACTIFS NUMERIQUES, JEUX','Sciences et sciences de lingénieur','Informatique',21,7,14,'86194','Poitiers','Vienne','A13','Poitiers','R75','Nouvelle-Aquitaine','0860856N','Université de Poitiers');
INSERT INTO masters VALUES (5,'Université','Université de Poitiers','Diplômes nationaux','Master','AUDIOVISUEL, MEDIAS INTERACTIFS NUMERIQUES, JEUX','Sciences et sciences de lingénieur','Informatique',17,5,12,'86194','Poitiers','Vienne','A13','Poitiers','R75','Nouvelle-Aquitaine','0860856N','Université de Poitiers');
INSERT INTO masters VALUES (6,'Autre établissement','Institut national universitaire Jean-François Champollion','Diplômes nationaux','Master','AUDIOVISUEL, MEDIAS INTERACTIFS NUMERIQUES, JEUX','Sciences et sciences de lingénieur','Informatique',16,3,13,'81004','Albi','Tarn','A16','Toulouse','R76','Occitanie','0811293R','Institut national universitaire Jean-François Champollion');
INSERT INTO masters VALUES (7,'Université','Université de Tours','Diplômes nationaux','Master','INFORMATIQUE','Sciences et sciences de lingénieur','Informatique',21,9,12,'37261','Tours','Indre-et-Loire','A18','Orléans-Tours','R24','Centre-Val de Loire','0370800U','Université de Tours');
INSERT INTO masters VALUES (8,'École','Institut national des sciences appliquées de Rennes','Diplômes nationaux','Master','INFORMATIQUE','Sciences et sciences de lingénieur','Informatique',0,0,0,'35238','Rennes','Ille-et-Vilaine','A14','Rennes','R53','Bretagne','0350097R','Institut national des sciences appliquées de Rennes');
INSERT INTO masters VALUES (9,'Université','Université de Bordeaux','Diplômes nationaux','Master','INFORMATIQUE','Sciences et sciences de lingénieur','Informatique',151,18,133,'33522','Talence','Gironde','A04','Bordeaux','R75','Nouvelle-Aquitaine','0333298F','Université de Bordeaux');
INSERT INTO masters VALUES (10,'Université','Université de Caen Normandie','Diplômes nationaux','Master','INFORMATIQUE','Sciences et sciences de lingénieur','Informatique',71,14,57,'14118','Caen','Calvados','A70','Normandie','R28','Normandie','0141408E','Université de Caen Normandie');
INSERT INTO masters VALUES (11,'Université','Université de Caen Normandie','Diplômes nationaux','Master','INFORMATIQUE','Sciences et sciences de lingénieur','Informatique',91,9,82,'14118','Caen','Calvados','A70','Normandie','R28','Normandie','0141408E','Université de Caen Normandie');
INSERT INTO masters VALUES (12,'Université','Université de Bourgogne','Diplômes nationaux','Master','INFORMATIQUE','Sciences et sciences de lingénieur','Informatique',60,13,47,'21231','Dijon','Côte-dOr','A07','Dijon','R27','Bourgogne-Franche-Comté','0211237F','Université de Bourgogne');
INSERT INTO masters VALUES (13,'Université','Université de Corse Pasquale Paoli','Diplômes nationaux','Master','INFORMATIQUE','Sciences et sciences de lingénieur','Informatique',21,7,14,'2B096','Corte','Haute-Corse','A27','Corse','R94','Corse','7200664J','Université de Corse Pasquale Paoli');
INSERT INTO masters VALUES (14,'Université','Université de Bretagne Occidentale','Diplômes nationaux','Master','INFORMATIQUE','Sciences et sciences de lingénieur','Informatique',92,19,73,'29019','Brest','Finistère','A14','Rennes','R53','Bretagne','0290346U','Université de Bretagne Occidentale');
INSERT INTO masters VALUES (15,'Université','Université de Corse Pasquale Paoli','Diplômes nationaux','Master','INFORMATIQUE','Sciences et sciences de lingénieur','Informatique',14,2,12,'2B096','Corte','Haute-Corse','A27','Corse','R94','Corse','7200664J','Université de Corse Pasquale Paoli');
INSERT INTO masters VALUES (16,'Université','Université Paris Cité','Diplômes nationaux','Master','INFORMATIQUE','Sciences et sciences de lingénieur','Informatique',15,3,12,'75113','Paris 13e','Paris','A01','Paris','R11','Île-de-France','0755976N','Université Paris Cité');
INSERT INTO masters VALUES (17,'Université','Université Paris Cité','Diplômes nationaux','Master','INFORMATIQUE','Sciences et sciences de lingénieur','Informatique',13,2,11,'75113','Paris 13e','Paris','A01','Paris','R11','Île-de-France','0755976N','Université Paris Cité');
INSERT INTO masters VALUES (18,'Université','Université Paris Cité','Diplômes nationaux','Master','INFORMATIQUE','Sciences et sciences de lingénieur','Informatique',205,64,141,'75106','Paris  6e','Paris','A01','Paris','R11','Île-de-France','0755976N','Université Paris Cité');
INSERT INTO masters VALUES (19,'Université','Université Claude Bernard - Lyon 1','Diplômes nationaux','Master','INFORMATIQUE','Sciences et sciences de lingénieur','Informatique',147,25,122,'69266','Villeurbanne','Rhône','A10','Lyon','R84','Auvergne-Rhône-Alpes','0691774D','Université Claude Bernard - Lyon 1');
INSERT INTO masters VALUES (20,'Université','Sorbonne Université','Diplômes nationaux','Master','INFORMATIQUE','Sciences et sciences de lingénieur','Informatique',345,94,251,'75105','Paris  5e','Paris','A01','Paris','R11','Île-de-France','0755890V','Sorbonne Université');
INSERT INTO masters VALUES (21,'Grand établissement','Université de Lorraine','Diplômes nationaux','Master','INFORMATIQUE','Sciences et sciences de lingénieur','Informatique',62,11,51,'57463','Metz','Moselle','A12','Nancy-Metz','R44','Grand Est','0542493S','Université de Lorraine');
INSERT INTO masters VALUES (22,'Université','Université Bretagne Sud','Diplômes nationaux','Master','INFORMATIQUE','Sciences et sciences de lingénieur','Informatique',57,19,38,'56260','Vannes','Morbihan','A14','Rennes','R53','Bretagne','0561718N','Université Bretagne Sud');
INSERT INTO masters VALUES (23,'Université','Université Bretagne Sud','Diplômes nationaux','Master','INFORMATIQUE','Sciences et sciences de lingénieur','Informatique',75,26,49,'56260','Vannes','Morbihan','A14','Rennes','R53','Bretagne','0561718N','Université Bretagne Sud');
INSERT INTO masters VALUES (24,'Université','Université du Littoral Côte dOpale','Diplômes nationaux','Master','INFORMATIQUE','Sciences et sciences de lingénieur','Informatique',37,1,36,'62193','Calais','Pas-de-Calais','A09','Lille','R32','Hauts-de-France','0595964M','Université du Littoral Côte dOpale');
INSERT INTO masters VALUES (25,'Université','Université Polytechnique Hauts-de-France','Diplômes nationaux','Master','INFORMATIQUE','Sciences et sciences de lingénieur','Informatique',50,6,44,'59606','Valenciennes','Nord','A09','Lille','R32','Hauts-de-France','0597131F','Université Polytechnique Hauts-de-France');
INSERT INTO masters VALUES (26,'Université','Université de Pau et des Pays de lAdour','Diplômes nationaux','Master','INFORMATIQUE','Sciences et sciences de lingénieur','Informatique',30,6,24,'64024','Anglet','Pyrénées-Atlantiques','A04','Bordeaux','R75','Nouvelle-Aquitaine','0640251A','Université de Pau et des Pays de lAdour');
INSERT INTO masters VALUES (27,'Université','Université Clermont Auvergne','Diplômes nationaux','Master','INFORMATIQUE','Sciences et sciences de lingénieur','Informatique',48,8,40,'63113','Clermont-Ferrand','Puy-de-Dôme','A06','Clermont-Ferrand','R84','Auvergne-Rhône-Alpes','0632084Y','Université Clermont Auvergne');
INSERT INTO masters VALUES (28,'Université','Université Paris 8 - Vincennes - Saint-Denis','Diplômes nationaux','Master','INFORMATIQUE','Sciences et sciences de lingénieur','Informatique',73,27,46,'93066','Saint-Denis','Seine-Saint-Denis','A24','Créteil','R11','Île-de-France','0931827F','Université Paris 8 - Vincennes - Saint-Denis');
INSERT INTO masters VALUES (29,'Université','Université Sorbonne Paris Nord','Diplômes nationaux','Master','INFORMATIQUE','Sciences et sciences de lingénieur','Informatique',47,18,29,'93079','Villetaneuse','Seine-Saint-Denis','A24','Créteil','R11','Île-de-France','0931238R','Université Sorbonne Paris Nord');
INSERT INTO masters VALUES (30,'Université','Université des Antilles','Diplômes nationaux','Master','INFORMATIQUE','Sciences et sciences de lingénieur','Informatique',10,0,10,'97120','Pointe-à-Pitre','Guadeloupe','A32','Guadeloupe','R01','Guadeloupe','9710585J','Université des Antilles');
INSERT INTO masters VALUES (31,'Université','Université Paris-Saclay','Diplômes nationaux','Master','INFORMATIQUE','Sciences et sciences de lingénieur','Informatique',131,40,91,'91471','Orsay','Essonne','A25','Versailles','R11','Île-de-France','0912408Y','Université Paris-Saclay');
INSERT INTO masters VALUES (32,'Université','Université de Toulon','Diplômes nationaux','Master','INFORMATIQUE','Sciences et sciences de lingénieur','Informatique',12,2,10,'83062','La Garde','Var','A23','Nice','R93','Provence-Alpes-Côte dAzur','0830766G','Université de Toulon');
INSERT INTO masters VALUES (33,'École','École nationale supérieure de mécanique et daérotechnique de Poitiers','Diplômes nationaux','Master','INFORMATIQUE','Sciences et sciences de lingénieur','Informatique',4,2,2,'86062','Chasseneuil-du-Poitou','Vienne','A13','Poitiers','R75','Nouvelle-Aquitaine','0860073M','École nationale supérieure de mécanique et daérotechnique de Poitiers');
INSERT INTO masters VALUES (34,'Université','Université Paris-Saclay','Diplômes nationaux','Master','INFORMATIQUE','Sciences et sciences de lingénieur','Informatique',151,35,116,'78646','Versailles','Yvelines','A25','Versailles','R11','Île-de-France','0912408Y','Université Paris-Saclay');
INSERT INTO masters VALUES (35,'École','Institut national des sciences appliquées de Toulouse','Diplômes nationaux','Master','RESEAUX ET TELECOMMUNICATION','Sciences et sciences de lingénieur','Informatique',1,0,1,'31555','Toulouse','Haute-Garonne','A16','Toulouse','R76','Occitanie','0310152X','Institut national des sciences appliquées de Toulouse');
INSERT INTO masters VALUES (36,'Université','Université Polytechnique Hauts-de-France','Diplômes nationaux','Master','RESEAUX ET TELECOMMUNICATION','Sciences et sciences de lingénieur','Informatique',3,1,2,'59392','Maubeuge','Nord','A09','Lille','R32','Hauts-de-France','0597131F','Université Polytechnique Hauts-de-France');
INSERT INTO masters VALUES (37,'Université','Nantes Université','Diplômes nationaux','Master','METHODES INFORMATIQUES APPLIQUEES A LA GESTION DES ENTREPRISES-MIAGE','Sciences et sciences de lingénieur','Informatique',43,9,34,'44109','Nantes','Loire-Atlantique','A17','Nantes','R52','Pays de la Loire','0442953W','Nantes Université');
INSERT INTO masters VALUES (38,'Université','Nantes Université','Diplômes nationaux','Master','METHODES INFORMATIQUES APPLIQUEES A LA GESTION DES ENTREPRISES-MIAGE','Sciences et sciences de lingénieur','Informatique',34,6,28,'44109','Nantes','Loire-Atlantique','A17','Nantes','R52','Pays de la Loire','0442953W','Nantes Université');
INSERT INTO masters VALUES (39,'Université','Université dOrléans','Diplômes nationaux','Master','METHODES INFORMATIQUES APPLIQUEES A LA GESTION DES ENTREPRISES-MIAGE','Sciences et sciences de lingénieur','Informatique',84,16,68,'45234','Orléans','Loiret','A18','Orléans-Tours','R24','Centre-Val de Loire','0450855K','Université dOrléans');
INSERT INTO masters VALUES (40,'Université','Aix-Marseille Université','Diplômes nationaux','Master','METHODES INFORMATIQUES APPLIQUEES A LA GESTION DES ENTREPRISES-MIAGE','Sciences et sciences de lingénieur','Informatique',30,8,22,'13201','Marseille  1er','Bouches-du-Rhône','A02','Aix-Marseille','R93','Provence-Alpes-Côte dAzur','0134009M','Aix-Marseille Université');
INSERT INTO masters VALUES (41,'Université','Université Toulouse III - Paul Sabatier','Diplômes nationaux','Master','METHODES INFORMATIQUES APPLIQUEES A LA GESTION DES ENTREPRISES-MIAGE','Sciences et sciences de lingénieur','Informatique',62,15,47,'31555','Toulouse','Haute-Garonne','A16','Toulouse','R76','Occitanie','0311384L','Université Toulouse III - Paul Sabatier');
INSERT INTO masters VALUES (42,'Université','Université Toulouse Capitole','Diplômes nationaux','Master','METHODES INFORMATIQUES APPLIQUEES A LA GESTION DES ENTREPRISES-MIAGE','Sciences et sciences de lingénieur','Informatique',86,42,44,'31555','Toulouse','Haute-Garonne','A16','Toulouse','R76','Occitanie','0311382J','Université Toulouse Capitole');
INSERT INTO masters VALUES (43,'Grand établissement','Université de Lorraine','Diplômes nationaux','Master','METHODES INFORMATIQUES APPLIQUEES A LA GESTION DES ENTREPRISES-MIAGE','Sciences et sciences de lingénieur','Informatique',80,19,61,'54395','Nancy','Meurthe-et-Moselle','A12','Nancy-Metz','R44','Grand Est','0542493S','Université de Lorraine');
INSERT INTO masters VALUES (44,'Université','Université de Lille','Diplômes nationaux','Master','METHODES INFORMATIQUES APPLIQUEES A LA GESTION DES ENTREPRISES-MIAGE','Sciences et sciences de lingénieur','Informatique',38,6,32,'59009','Villeneuve-dAscq','Nord','A09','Lille','R32','Hauts-de-France','0597239Y','Université de Lille');
INSERT INTO masters VALUES (45,'Université','Université Claude Bernard - Lyon 1','Diplômes nationaux','Master','METHODES INFORMATIQUES APPLIQUEES A LA GESTION DES ENTREPRISES-MIAGE','Sciences et sciences de lingénieur','Informatique',25,11,14,'69266','Villeurbanne','Rhône','A10','Lyon','R84','Auvergne-Rhône-Alpes','0691774D','Université Claude Bernard - Lyon 1');
INSERT INTO masters VALUES (46,'Université','Université Paris 1 - Panthéon Sorbonne','Diplômes nationaux','Master','METHODES INFORMATIQUES APPLIQUEES A LA GESTION DES ENTREPRISES-MIAGE','Sciences et sciences de lingénieur','Informatique',47,22,25,'75113','Paris 13e','Paris','A01','Paris','R11','Île-de-France','0751717J','Université Paris 1 - Panthéon Sorbonne');
INSERT INTO masters VALUES (47,'Université','Université des Antilles','Diplômes nationaux','Master','METHODES INFORMATIQUES APPLIQUEES A LA GESTION DES ENTREPRISES-MIAGE','Sciences et sciences de lingénieur','Informatique',14,2,12,'97120','Pointe-à-Pitre','Guadeloupe','A32','Guadeloupe','R01','Guadeloupe','9710585J','Université des Antilles');
INSERT INTO masters VALUES (48,'Université','Université Paris-Saclay','Diplômes nationaux','Master','METHODES INFORMATIQUES APPLIQUEES A LA GESTION DES ENTREPRISES-MIAGE','Sciences et sciences de lingénieur','Informatique',56,26,30,'91471','Orsay','Essonne','A25','Versailles','R11','Île-de-France','0912408Y','Université Paris-Saclay');
INSERT INTO masters VALUES (49,'Université','Université Paris-Saclay','Diplômes nationaux','Master','METHODES INFORMATIQUES APPLIQUEES A LA GESTION DES ENTREPRISES-MIAGE','Sciences et sciences de lingénieur','Informatique',44,10,34,'91228','Évry-Courcouronnes','Essonne','A25','Versailles','R11','Île-de-France','0912408Y','Université Paris-Saclay');
INSERT INTO masters VALUES (50,'École','École normale supérieure de Rennes','Diplômes détablissement','Diplômes détablissement','DIPLOMES DUNIVERSITE EN INFORMATIQUE - BAC+2 A BAC+5','Sciences et sciences de lingénieur','Informatique',66,7,59,'35047','Bruz','Ille-et-Vilaine','A14','Rennes','R53','Bretagne','0352440M','École normale supérieure de Rennes');
INSERT INTO masters VALUES (51,'Université','Université Grenoble Alpes','Diplômes détablissement','Diplômes détablissement','DIPLOMES DUNIVERSITE EN INFORMATIQUE - BAC+2 A BAC+5','Sciences et sciences de lingénieur','Informatique',0,0,0,'38421','Saint-Martin-dHères','Isère','A08','Grenoble','R84','Auvergne-Rhône-Alpes','0383546Y','Université Grenoble Alpes');
INSERT INTO masters VALUES (52,'École','Centrale Marseille','Diplômes détablissement','Diplômes détablissement','MASTERES SPECIALISES EN INFORMATIQUE - BAC+5 A BAC+6 ET PLUS','Sciences et sciences de lingénieur','Informatique',13,3,10,'13213','Marseille 13e','Bouches-du-Rhône','A02','Aix-Marseille','R93','Provence-Alpes-Côte dAzur','0133774G','Centrale Marseille');
INSERT INTO masters VALUES (53,'École','Institut national des sciences appliquées de Toulouse','Diplômes détablissement','Diplômes détablissement','MASTERES SPECIALISES EN INFORMATIQUE - BAC+5 A BAC+6 ET PLUS','Sciences et sciences de lingénieur','Informatique',4,2,2,'31555','Toulouse','Haute-Garonne','A16','Toulouse','R76','Occitanie','0310152X','Institut national des sciences appliquées de Toulouse');
INSERT INTO masters VALUES (54,'Université','Nantes Université','Diplômes détablissement','Diplômes détablissement','DIPLOMES DUNIVERSITE EN INFORMATIQUE - BAC+2 A BAC+4','Sciences et sciences de lingénieur','Informatique',8,2,6,'44109','Nantes','Loire-Atlantique','A17','Nantes','R52','Pays de la Loire','0442953W','Nantes Université');
INSERT INTO masters VALUES (55,'Université','Université Paris-Saclay','Diplômes détablissement','Diplômes détablissement','NON DETAILLE','Sciences et sciences de lingénieur','Informatique',98,11,87,'91272','Gif-sur-Yvette','Essonne','A25','Versailles','R11','Île-de-France','0912423P','Université Paris-Saclay');
INSERT INTO masters VALUES (56,'Université','Université Sorbonne Paris Nord','Diplômes nationaux','Master','INGENIERIE ET INNOVATION EN IMAGES ET RESEAUX','Sciences et sciences de lingénieur','Informatique',22,8,14,'93079','Villetaneuse','Seine-Saint-Denis','A24','Créteil','R11','Île-de-France','0931238R','Université Sorbonne Paris Nord');
INSERT INTO masters VALUES (57,'Université','Université dOrléans','Diplômes détablissement','Diplômes détablissement','DIPLOMES DUNIVERSITE EN INFORMATIQUE - BAC+4','Sciences et sciences de lingénieur','Informatique',1,0,1,'45234','Orléans','Loiret','A18','Orléans-Tours','R24','Centre-Val de Loire','0450855K','Université dOrléans');
INSERT INTO masters VALUES (58,'Université','Aix-Marseille Université','Diplômes détablissement','Diplômes détablissement','DIPLOMES DUNIVERSITE EN INFORMATIQUE - BAC+4 A BAC+5','Sciences et sciences de lingénieur','Informatique',0,0,0,'13213','Marseille 13e','Bouches-du-Rhône','A02','Aix-Marseille','R93','Provence-Alpes-Côte dAzur','0134009M','Aix-Marseille Université');
INSERT INTO masters VALUES (59,'Grand établissement','Université de Lorraine','Diplômes nationaux','Master','AUDIOVISUEL, MEDIAS INTERACTIFS NUMERIQUES, JEUX','Sciences et sciences de lingénieur','Informatique',35,15,20,'57463','Metz','Moselle','A12','Nancy-Metz','R44','Grand Est','0542493S','Université de Lorraine');
INSERT INTO masters VALUES (60,'Université','Université Jean Monnet','Diplômes nationaux','Master','INFORMATIQUE','Sciences et sciences de lingénieur','Informatique',47,11,36,'42218','Saint-Étienne','Loire','A10','Lyon','R84','Auvergne-Rhône-Alpes','0421095M','Université Jean Monnet');
INSERT INTO masters VALUES (61,'Université','Université Grenoble Alpes','Diplômes nationaux','Master','INFORMATIQUE','Sciences et sciences de lingénieur','Informatique',35,11,24,'38421','Saint-Martin-dHères','Isère','A08','Grenoble','R84','Auvergne-Rhône-Alpes','0381912X','Université Grenoble Alpes');
INSERT INTO masters VALUES (62,'Université','Université dOrléans','Diplômes nationaux','Master','INFORMATIQUE','Sciences et sciences de lingénieur','Informatique',36,4,32,'45234','Orléans','Loiret','A18','Orléans-Tours','R24','Centre-Val de Loire','0450855K','Université dOrléans');
INSERT INTO masters VALUES (63,'Université','Université de Montpellier','Diplômes nationaux','Master','INFORMATIQUE','Sciences et sciences de lingénieur','Informatique',146,45,101,'34172','Montpellier','Hérault','A11','Montpellier','R76','Occitanie','0342490X','Université de Montpellier');
INSERT INTO masters VALUES (64,'École','Institut national des sciences appliquées Centre Val de Loire','Diplômes nationaux','Master','INFORMATIQUE','Sciences et sciences de lingénieur','Informatique',0,0,0,'18033','Bourges','Cher','A18','Orléans-Tours','R24','Centre-Val de Loire','0180974L','Institut national des sciences appliquées Centre Val de Loire');
INSERT INTO masters VALUES (65,'École','Centrale Marseille','Diplômes nationaux','Master','INFORMATIQUE','Sciences et sciences de lingénieur','Informatique',0,0,0,'13213','Marseille 13e','Bouches-du-Rhône','A02','Aix-Marseille','R93','Provence-Alpes-Côte dAzur','0133774G','Centrale Marseille');
INSERT INTO masters VALUES (66,'Université','Université de Picardie Jules-Verne','Diplômes nationaux','Master','INFORMATIQUE','Sciences et sciences de lingénieur','Informatique',15,0,15,2691,'Saint-Quentin','Aisne','A20','Amiens','R32','Hauts-de-France','0801344B','Université de Picardie Jules-Verne');
INSERT INTO masters VALUES (67,'Université','Université Le Havre Normandie','Diplômes nationaux','Master','INFORMATIQUE','Sciences et sciences de lingénieur','Informatique',41,6,35,'76351','Le Havre','Seine-Maritime','A70','Normandie','R28','Normandie','0762762P','Université Le Havre Normandie');
INSERT INTO masters VALUES (68,'Université','Université Gustave Eiffel','Diplômes nationaux','Master','INFORMATIQUE','Sciences et sciences de lingénieur','Informatique',103,24,79,'77083','Champs-sur-Marne','Seine-et-Marne','A24','Créteil','R11','Île-de-France','0772894C','Université Gustave Eiffel');
INSERT INTO masters VALUES (69,'École','Centrale Lyon','Diplômes nationaux','Master','INFORMATIQUE','Sciences et sciences de lingénieur','Informatique',8,3,5,'69081','Écully','Rhône','A10','Lyon','R84','Auvergne-Rhône-Alpes','0690187D','Centrale Lyon');
INSERT INTO masters VALUES (70,'Université','Université Lumière - Lyon 2','Diplômes nationaux','Master','INFORMATIQUE','Sciences et sciences de lingénieur','Informatique',61,22,39,'69029','Bron','Rhône','A10','Lyon','R84','Auvergne-Rhône-Alpes','0691775E','Université Lumière - Lyon 2');
INSERT INTO masters VALUES (71,'Université','Université Savoie Mont Blanc','Diplômes nationaux','Master','INFORMATIQUE','Sciences et sciences de lingénieur','Informatique',30,3,27,'73051','Le Bourget-du-Lac','Savoie','A08','Grenoble','R84','Auvergne-Rhône-Alpes','0730858L','Université Savoie Mont Blanc');
INSERT INTO masters VALUES (72,'Université','Le Mans Université','Diplômes nationaux','Master','INFORMATIQUE','Sciences et sciences de lingénieur','Informatique',29,3,26,'72181','Le Mans','Sarthe','A17','Nantes','R52','Pays de la Loire','0720916E','Le Mans Université');
INSERT INTO masters VALUES (73,'Université','Sorbonne Université','Diplômes nationaux','Master','INFORMATIQUE','Sciences et sciences de lingénieur','Informatique',424,115,309,'75105','Paris  5e','Paris','A01','Paris','R11','Île-de-France','0755890V','Sorbonne Université');
INSERT INTO masters VALUES (74,'Université','Université dAngers','Diplômes nationaux','Master','INFORMATIQUE','Sciences et sciences de lingénieur','Informatique',28,4,24,'49007','Angers','Maine-et-Loire','A17','Nantes','R52','Pays de la Loire','0490970N','Université dAngers');
INSERT INTO masters VALUES (75,'Université','Université de Pau et des Pays de lAdour','Diplômes nationaux','Master','INFORMATIQUE','Sciences et sciences de lingénieur','Informatique',12,3,9,'64024','Anglet','Pyrénées-Atlantiques','A04','Bordeaux','R75','Nouvelle-Aquitaine','0640251A','Université de Pau et des Pays de lAdour');
INSERT INTO masters VALUES (76,'Université','Université Paris-Est Créteil','Diplômes nationaux','Master','INFORMATIQUE','Sciences et sciences de lingénieur','Informatique',16,3,13,'94028','Créteil','Val-de-Marne','A24','Créteil','R11','Île-de-France','0941111X','Université Paris-Est Créteil');
INSERT INTO masters VALUES (77,'Université','Université de Limoges','Diplômes nationaux','Master','INFORMATIQUE','Sciences et sciences de lingénieur','Informatique',64,19,45,'87085','Limoges','Haute-Vienne','A22','Limoges','R75','Nouvelle-Aquitaine','0870669E','Université de Limoges');
INSERT INTO masters VALUES (78,'Université','Université de Bretagne Occidentale','Diplômes nationaux','Master','RESEAUX ET TELECOMMUNICATION','Sciences et sciences de lingénieur','Informatique',44,16,28,'29019','Brest','Finistère','A14','Rennes','R53','Bretagne','0290346U','Université de Bretagne Occidentale');
INSERT INTO masters VALUES (79,'Université','Université Polytechnique Hauts-de-France','Diplômes nationaux','Master','RESEAUX ET TELECOMMUNICATION','Sciences et sciences de lingénieur','Informatique',36,8,28,'59606','Valenciennes','Nord','A09','Lille','R32','Hauts-de-France','0597131F','Université Polytechnique Hauts-de-France');
INSERT INTO masters VALUES (80,'Université','Université Savoie Mont Blanc','Diplômes nationaux','Master','RESEAUX ET TELECOMMUNICATION','Sciences et sciences de lingénieur','Informatique',26,2,24,'73051','Le Bourget-du-Lac','Savoie','A08','Grenoble','R84','Auvergne-Rhône-Alpes','0730858L','Université Savoie Mont Blanc');
INSERT INTO masters VALUES (81,'Université','Université de Rennes 1','Diplômes nationaux','Master','METHODES INFORMATIQUES APPLIQUEES A LA GESTION DES ENTREPRISES-MIAGE','Sciences et sciences de lingénieur','Informatique',88,25,63,'35238','Rennes','Ille-et-Vilaine','A14','Rennes','R53','Bretagne','0350936C','Université de Rennes');
INSERT INTO masters VALUES (82,'Grand établissement','Université de Lorraine','Diplômes nationaux','Master','METHODES INFORMATIQUES APPLIQUEES A LA GESTION DES ENTREPRISES-MIAGE','Sciences et sciences de lingénieur','Informatique',58,13,45,'54395','Nancy','Meurthe-et-Moselle','A12','Nancy-Metz','R44','Grand Est','0542493S','Université de Lorraine');
INSERT INTO masters VALUES (83,'Université','Université de Haute-Alsace','Diplômes nationaux','Master','METHODES INFORMATIQUES APPLIQUEES A LA GESTION DES ENTREPRISES-MIAGE','Sciences et sciences de lingénieur','Informatique',28,8,20,'68224','Mulhouse','Haut-Rhin','A15','Strasbourg','R44','Grand Est','0681166Y','Université de Haute-Alsace');
INSERT INTO masters VALUES (84,'Université','Université Paris Cité','Diplômes nationaux','Master','METHODES INFORMATIQUES APPLIQUEES A LA GESTION DES ENTREPRISES-MIAGE','Sciences et sciences de lingénieur','Informatique',37,15,22,'75106','Paris  6e','Paris','A01','Paris','R11','Île-de-France','0755976N','Université Paris Cité');
INSERT INTO masters VALUES (85,'Université','Université Paris 1 - Panthéon Sorbonne','Diplômes nationaux','Master','METHODES INFORMATIQUES APPLIQUEES A LA GESTION DES ENTREPRISES-MIAGE','Sciences et sciences de lingénieur','Informatique',51,19,32,'75113','Paris 13e','Paris','A01','Paris','R11','Île-de-France','0751717J','Université Paris 1 - Panthéon Sorbonne');
INSERT INTO masters VALUES (86,'Université','Université Paris Nanterre','Diplômes nationaux','Master','METHODES INFORMATIQUES APPLIQUEES A LA GESTION DES ENTREPRISES-MIAGE','Sciences et sciences de lingénieur','Informatique',46,20,26,'92050','Nanterre','Hauts-de-Seine','A25','Versailles','R11','Île-de-France','0921204J','Université Paris Nanterre');
INSERT INTO masters VALUES (87,'Université','Université Paris-Saclay','Diplômes nationaux','Master','METHODES INFORMATIQUES APPLIQUEES A LA GESTION DES ENTREPRISES-MIAGE','Sciences et sciences de lingénieur','Informatique',43,13,30,'91228','Évry-Courcouronnes','Essonne','A25','Versailles','R11','Île-de-France','0912408Y','Université Paris-Saclay');
INSERT INTO masters VALUES (88,'Université','Université de Picardie Jules-Verne','Diplômes nationaux','Master','METHODES INFORMATIQUES APPLIQUEES A LA GESTION DES ENTREPRISES-MIAGE','Sciences et sciences de lingénieur','Informatique',136,19,117,'80021','Amiens','Somme','A20','Amiens','R32','Hauts-de-France','0801344B','Université de Picardie Jules-Verne');
INSERT INTO masters VALUES (89,'Université','Université de Rouen Normandie','Diplômes nationaux','Master','SCIENCES ET INGENIERIE DES DONNEES','Sciences et sciences de lingénieur','Informatique',42,13,29,'76575','Saint-Étienne-du-Rouvray','Seine-Maritime','A70','Normandie','R28','Normandie','0761904G','Université de Rouen Normandie');
INSERT INTO masters VALUES (90,'École','Toulouse INP','Diplômes détablissement','Diplômes détablissement','DIPLOMES DUNIVERSITE EN INFORMATIQUE - BAC+4','Sciences et sciences de lingénieur','Informatique',19,1,18,'31555','Toulouse','Haute-Garonne','A16','Toulouse','R76','Occitanie','0311381H','Toulouse INP');
INSERT INTO masters VALUES (91,'Grand établissement','Université de Lorraine','Diplômes détablissement','Diplômes détablissement','DIPLOMES DUNIVERSITE EN INFORMATIQUE - BAC+5 A BAC+6 ET PLUS','Sciences et sciences de lingénieur','Informatique',12,1,11,'54395','Nancy','Meurthe-et-Moselle','A12','Nancy-Metz','R44','Grand Est','0542493S','Université de Lorraine');
INSERT INTO masters VALUES (92,'École','Université de technologie de Troyes','Diplômes détablissement','Diplômes détablissement','MASTERES SPECIALISES EN INFORMATIQUE - BAC+5 A BAC+6 ET PLUS','Sciences et sciences de lingénieur','Informatique',77,20,57,'10387','Troyes','Aube','A19','Reims','R44','Grand Est','0101060Y','Université de technologie de Troyes');
INSERT INTO masters VALUES (93,'École','Institut national des sciences appliquées de Rouen Normandie','Diplômes détablissement','Diplômes détablissement','MASTERES SPECIALISES EN INFORMATIQUE - BAC+5 A BAC+6 ET PLUS','Sciences et sciences de lingénieur','Informatique',13,4,9,'76575','Saint-Étienne-du-Rouvray','Seine-Maritime','A70','Normandie','R28','Normandie','0760165S','Institut national des sciences appliquées de Rouen Normandie');
INSERT INTO masters VALUES (94,'Université','Université Paris-Saclay','Diplômes détablissement','Diplômes détablissement','MASTERES SPECIALISES EN INFORMATIQUE - BAC+5 A BAC+6 ET PLUS','Sciences et sciences de lingénieur','Informatique',12,2,10,'91272','Gif-sur-Yvette','Essonne','A25','Versailles','R11','Île-de-France','0912341A','Université Paris-Saclay');
INSERT INTO masters VALUES (95,'Université','CY Cergy Paris Université','Diplômes détablissement','Diplômes détablissement','MASTERES SPECIALISES EN INFORMATIQUE - BAC+5 A BAC+6 ET PLUS','Sciences et sciences de lingénieur','Informatique',94,23,71,'95127','Cergy','Val-dOise','A25','Versailles','R11','Île-de-France','0952259P','CY Cergy Paris Université');
INSERT INTO masters VALUES (96,'Université','Université Paris-Saclay','Diplômes détablissement','Diplômes détablissement','MASTERS OF EN INFORMATIQUE - BAC+4 A BAC+5','Sciences et sciences de lingénieur','Informatique',10,1,9,'91272','Gif-sur-Yvette','Essonne','A25','Versailles','R11','Île-de-France','0912341A','Université Paris-Saclay');
INSERT INTO masters VALUES (97,'Université','Université Paris sciences et lettres','Diplômes nationaux','Autres formations','NON DETAILLE','Sciences et sciences de lingénieur','Informatique',256,140,116,'75116','Paris 16e','Paris','A01','Paris','R11','Île-de-France','0750736T','Université Paris sciences et lettres');
INSERT INTO masters VALUES (98,'Grand établissement','Université de Lorraine','Diplômes nationaux','Master','AUDIOVISUEL, MEDIAS INTERACTIFS NUMERIQUES, JEUX','Sciences et sciences de lingénieur','Informatique',44,19,25,'57463','Metz','Moselle','A12','Nancy-Metz','R44','Grand Est','0542493S','Université de Lorraine');
INSERT INTO masters VALUES (99,'Université','Université Jean Moulin - Lyon 3','Diplômes nationaux','Master','AUDIOVISUEL, MEDIAS INTERACTIFS NUMERIQUES, JEUX','Sciences et sciences de lingénieur','Informatique',21,12,9,'69387','Lyon 7e','Rhône','A10','Lyon','R84','Auvergne-Rhône-Alpes','0692437Z','Université Jean Moulin - Lyon 3');
INSERT INTO masters VALUES (100,'Autre établissement','Institut national universitaire Jean-François Champollion','Diplômes nationaux','Master','AUDIOVISUEL, MEDIAS INTERACTIFS NUMERIQUES, JEUX','Sciences et sciences de lingénieur','Informatique',17,4,13,'81004','Albi','Tarn','A16','Toulouse','R76','Occitanie','0811293R','Institut national universitaire Jean-François Champollion');
INSERT INTO masters VALUES (101,'Université','Université Grenoble Alpes','Diplômes nationaux','Master','INFORMATIQUE','Sciences et sciences de lingénieur','Informatique',42,5,37,'38421','Saint-Martin-dHères','Isère','A08','Grenoble','R84','Auvergne-Rhône-Alpes','0381912X','Université Grenoble Alpes');
INSERT INTO masters VALUES (102,'Université','Université dOrléans','Diplômes nationaux','Master','INFORMATIQUE','Sciences et sciences de lingénieur','Informatique',60,4,56,'45234','Orléans','Loiret','A18','Orléans-Tours','R24','Centre-Val de Loire','0450855K','Université dOrléans');
INSERT INTO masters VALUES (103,'Université','Nantes Université','Diplômes nationaux','Master','INFORMATIQUE','Sciences et sciences de lingénieur','Informatique',100,14,86,'44109','Nantes','Loire-Atlantique','A17','Nantes','R52','Pays de la Loire','0442953W','Nantes Université');
INSERT INTO masters VALUES (104,'Université','Nantes Université','Diplômes nationaux','Master','INFORMATIQUE','Sciences et sciences de lingénieur','Informatique',64,4,60,'44109','Nantes','Loire-Atlantique','A17','Nantes','R52','Pays de la Loire','0442953W','Nantes Université');
INSERT INTO masters VALUES (105,'Université','Université de Rennes 1','Diplômes nationaux','Master','INFORMATIQUE','Sciences et sciences de lingénieur','Informatique',120,18,102,'35238','Rennes','Ille-et-Vilaine','A14','Rennes','R53','Bretagne','0350936C','Université de Rennes');
INSERT INTO masters VALUES (106,'Université','Université de Rennes 1','Diplômes nationaux','Master','INFORMATIQUE','Sciences et sciences de lingénieur','Informatique',137,21,116,'35238','Rennes','Ille-et-Vilaine','A14','Rennes','R53','Bretagne','0350936C','Université de Rennes');
INSERT INTO masters VALUES (107,'Université','La Rochelle Université','Diplômes nationaux','Master','INFORMATIQUE','Sciences et sciences de lingénieur','Informatique',60,12,48,'17300','La Rochelle','Charente-Maritime','A13','Poitiers','R75','Nouvelle-Aquitaine','0171463Y','La Rochelle Université');
INSERT INTO masters VALUES (108,'Université','Aix-Marseille Université','Diplômes nationaux','Master','INFORMATIQUE','Sciences et sciences de lingénieur','Informatique',108,18,90,'13209','Marseille  9e','Bouches-du-Rhône','A02','Aix-Marseille','R93','Provence-Alpes-Côte dAzur','0134009M','Aix-Marseille Université');
INSERT INTO masters VALUES (109,'Université','Aix-Marseille Université','Diplômes nationaux','Master','INFORMATIQUE','Sciences et sciences de lingénieur','Informatique',80,7,73,'13209','Marseille  9e','Bouches-du-Rhône','A02','Aix-Marseille','R93','Provence-Alpes-Côte dAzur','0134009M','Aix-Marseille Université');
INSERT INTO masters VALUES (110,'Université','Université Côte dAzur','Diplômes nationaux','Master','INFORMATIQUE','Sciences et sciences de lingénieur','Informatique',81,17,64,6018,'Biot','Alpes-Maritimes','A23','Nice','R93','Provence-Alpes-Côte dAzur','0062205P','Université Côte dAzur');
INSERT INTO masters VALUES (111,'Université','Université Côte dAzur','Diplômes nationaux','Master','INFORMATIQUE','Sciences et sciences de lingénieur','Informatique',41,7,34,6018,'Biot','Alpes-Maritimes','A23','Nice','R93','Provence-Alpes-Côte dAzur','0062205P','Université Côte dAzur');
INSERT INTO masters VALUES (112,'Université','Université de Picardie Jules-Verne','Diplômes nationaux','Master','INFORMATIQUE','Sciences et sciences de lingénieur','Informatique',18,0,18,2691,'Saint-Quentin','Aisne','A20','Amiens','R32','Hauts-de-France','0801344B','Université de Picardie Jules-Verne');
INSERT INTO masters VALUES (113,'Université','Université de Franche-Comté','Diplômes nationaux','Master','INFORMATIQUE','Sciences et sciences de lingénieur','Informatique',138,32,106,'25056','Besançon','Doubs','A03','Besançon','R27','Bourgogne-Franche-Comté','0251215K','Université de Franche-Comté');
INSERT INTO masters VALUES (114,'Université','Université de Bourgogne','Diplômes nationaux','Master','INFORMATIQUE','Sciences et sciences de lingénieur','Informatique',50,5,45,'21231','Dijon','Côte-dOr','A07','Dijon','R27','Bourgogne-Franche-Comté','0211237F','Université de Bourgogne');
INSERT INTO masters VALUES (115,'École','Toulouse INP','Diplômes nationaux','Master','INFORMATIQUE','Sciences et sciences de lingénieur','Informatique',9,3,6,'31555','Toulouse','Haute-Garonne','A16','Toulouse','R76','Occitanie','0311381H','Toulouse INP');
INSERT INTO masters VALUES (116,'Université','Université de Bretagne Occidentale','Diplômes nationaux','Master','INFORMATIQUE','Sciences et sciences de lingénieur','Informatique',117,18,99,'29019','Brest','Finistère','A14','Rennes','R53','Bretagne','0290346U','Université de Bretagne Occidentale');
INSERT INTO masters VALUES (117,'Université','Université de Rouen Normandie','Diplômes nationaux','Master','INFORMATIQUE','Sciences et sciences de lingénieur','Informatique',86,15,71,'76575','Saint-Étienne-du-Rouvray','Seine-Maritime','A70','Normandie','R28','Normandie','0761904G','Université de Rouen Normandie');
INSERT INTO masters VALUES (118,'Université','Université Claude Bernard - Lyon 1','Diplômes nationaux','Master','INFORMATIQUE','Sciences et sciences de lingénieur','Informatique',151,18,133,'69266','Villeurbanne','Rhône','A10','Lyon','R84','Auvergne-Rhône-Alpes','0691774D','Université Claude Bernard - Lyon 1');
INSERT INTO masters VALUES (119,'Université','Université de Haute-Alsace','Diplômes nationaux','Master','INFORMATIQUE','Sciences et sciences de lingénieur','Informatique',11,0,11,'68224','Mulhouse','Haut-Rhin','A15','Strasbourg','R44','Grand Est','0681166Y','Université de Haute-Alsace');
INSERT INTO masters VALUES (120,'Université','Université Lumière - Lyon 2','Diplômes nationaux','Master','INFORMATIQUE','Sciences et sciences de lingénieur','Informatique',189,65,124,'69029','Bron','Rhône','A10','Lyon','R84','Auvergne-Rhône-Alpes','0691775E','Université Lumière - Lyon 2');
INSERT INTO masters VALUES (121,'Université','Université Paris sciences et lettres','Diplômes nationaux','Master','INFORMATIQUE','Sciences et sciences de lingénieur','Informatique',10,1,9,'75105','Paris  5e','Paris','A01','Paris','R11','Île-de-France','0753455Y','Université Paris sciences et lettres');
INSERT INTO masters VALUES (122,'Université','Université de Reims Champagne-Ardenne','Diplômes nationaux','Master','INFORMATIQUE','Sciences et sciences de lingénieur','Informatique',35,5,30,'51454','Reims','Marne','A19','Reims','R44','Grand Est','0511296G','Université de Reims Champagne-Ardenne');
INSERT INTO masters VALUES (123,'Université','Université dAngers','Diplômes nationaux','Master','INFORMATIQUE','Sciences et sciences de lingénieur','Informatique',30,3,27,'49007','Angers','Maine-et-Loire','A17','Nantes','R52','Pays de la Loire','0490970N','Université dAngers');
INSERT INTO masters VALUES (124,'Université','Université dArtois','Diplômes nationaux','Master','INFORMATIQUE','Sciences et sciences de lingénieur','Informatique',42,2,40,'62498','Lens','Pas-de-Calais','A09','Lille','R32','Hauts-de-France','0623957P','Université dArtois');
INSERT INTO masters VALUES (125,'Université','Université de Pau et des Pays de lAdour','Diplômes nationaux','Master','INFORMATIQUE','Sciences et sciences de lingénieur','Informatique',38,7,31,'64445','Pau','Pyrénées-Atlantiques','A04','Bordeaux','R75','Nouvelle-Aquitaine','0640251A','Université de Pau et des Pays de lAdour');
INSERT INTO masters VALUES (126,'Université','Université Paris 8 - Vincennes - Saint-Denis','Diplômes nationaux','Master','INFORMATIQUE','Sciences et sciences de lingénieur','Informatique',125,46,79,'93066','Saint-Denis','Seine-Saint-Denis','A24','Créteil','R11','Île-de-France','0931827F','Université Paris 8 - Vincennes - Saint-Denis');
INSERT INTO masters VALUES (127,'Université','Université Sorbonne Paris Nord','Diplômes nationaux','Master','INFORMATIQUE','Sciences et sciences de lingénieur','Informatique',80,37,43,'93079','Villetaneuse','Seine-Saint-Denis','A24','Créteil','R11','Île-de-France','0931238R','Université Sorbonne Paris Nord');
INSERT INTO masters VALUES (128,'Université','Université de La Réunion','Diplômes nationaux','Master','INFORMATIQUE','Sciences et sciences de lingénieur','Informatique',20,4,16,'97411','Saint-Denis','La Réunion','A28','La Réunion','R04','La Réunion','9740478B','Université de La Réunion');
INSERT INTO masters VALUES (129,'Université','Université de Limoges','Diplômes nationaux','Master','INFORMATIQUE','Sciences et sciences de lingénieur','Informatique',70,19,51,'87085','Limoges','Haute-Vienne','A22','Limoges','R75','Nouvelle-Aquitaine','0870669E','Université de Limoges');
INSERT INTO masters VALUES (130,'Université','Université de Poitiers','Diplômes nationaux','Master','INFORMATIQUE','Sciences et sciences de lingénieur','Informatique',30,1,29,'86194','Poitiers','Vienne','A13','Poitiers','R75','Nouvelle-Aquitaine','0860856N','Université de Poitiers');
INSERT INTO masters VALUES (131,'Université','Université Paris-Saclay','Diplômes nationaux','Master','INFORMATIQUE','Sciences et sciences de lingénieur','Informatique',195,47,148,'78646','Versailles','Yvelines','A25','Versailles','R11','Île-de-France','0912408Y','Université Paris-Saclay');
INSERT INTO masters VALUES (132,'Université','Université Toulouse III - Paul Sabatier','Diplômes nationaux','Master','RESEAUX ET TELECOMMUNICATION','Sciences et sciences de lingénieur','Informatique',41,7,34,'31555','Toulouse','Haute-Garonne','A16','Toulouse','R76','Occitanie','0311384L','Université Toulouse III - Paul Sabatier');
INSERT INTO masters VALUES (133,'Université','Aix-Marseille Université','Diplômes nationaux','Master','RESEAUX ET TELECOMMUNICATION','Sciences et sciences de lingénieur','Informatique',28,8,20,'13209','Marseille  9e','Bouches-du-Rhône','A02','Aix-Marseille','R93','Provence-Alpes-Côte dAzur','0134009M','Aix-Marseille Université');
INSERT INTO masters VALUES (134,'Université','Aix-Marseille Université','Diplômes nationaux','Master','RESEAUX ET TELECOMMUNICATION','Sciences et sciences de lingénieur','Informatique',47,12,35,'13209','Marseille  9e','Bouches-du-Rhône','A02','Aix-Marseille','R93','Provence-Alpes-Côte dAzur','0134009M','Aix-Marseille Université');
INSERT INTO masters VALUES (135,'Université','Université de Reims Champagne-Ardenne','Diplômes nationaux','Master','RESEAUX ET TELECOMMUNICATION','Sciences et sciences de lingénieur','Informatique',35,0,35,'51454','Reims','Marne','A19','Reims','R44','Grand Est','0511296G','Université de Reims Champagne-Ardenne');
INSERT INTO masters VALUES (136,'Université','Université de Bordeaux','Diplômes nationaux','Master','METHODES INFORMATIQUES APPLIQUEES A LA GESTION DES ENTREPRISES-MIAGE','Sciences et sciences de lingénieur','Informatique',44,15,29,'33522','Talence','Gironde','A04','Bordeaux','R75','Nouvelle-Aquitaine','0333298F','Université de Bordeaux');
INSERT INTO masters VALUES (137,'Université','Aix-Marseille Université','Diplômes nationaux','Master','METHODES INFORMATIQUES APPLIQUEES A LA GESTION DES ENTREPRISES-MIAGE','Sciences et sciences de lingénieur','Informatique',49,8,41,'13201','Marseille  1er','Bouches-du-Rhône','A02','Aix-Marseille','R93','Provence-Alpes-Côte dAzur','0134009M','Aix-Marseille Université');
INSERT INTO masters VALUES (138,'Université','Université Côte dAzur','Diplômes nationaux','Master','METHODES INFORMATIQUES APPLIQUEES A LA GESTION DES ENTREPRISES-MIAGE','Sciences et sciences de lingénieur','Informatique',187,45,142,6018,'Biot','Alpes-Maritimes','A23','Nice','R93','Provence-Alpes-Côte dAzur','0062205P','Université Côte dAzur');
INSERT INTO masters VALUES (139,'Université','Université de Haute-Alsace','Diplômes nationaux','Master','METHODES INFORMATIQUES APPLIQUEES A LA GESTION DES ENTREPRISES-MIAGE','Sciences et sciences de lingénieur','Informatique',28,8,20,'68224','Mulhouse','Haut-Rhin','A15','Strasbourg','R44','Grand Est','0681166Y','Université de Haute-Alsace');
INSERT INTO masters VALUES (140,'Université','Université Claude Bernard - Lyon 1','Diplômes nationaux','Master','METHODES INFORMATIQUES APPLIQUEES A LA GESTION DES ENTREPRISES-MIAGE','Sciences et sciences de lingénieur','Informatique',23,6,17,'69266','Villeurbanne','Rhône','A10','Lyon','R84','Auvergne-Rhône-Alpes','0691774D','Université Claude Bernard - Lyon 1');
INSERT INTO masters VALUES (141,'Université','Université Paris-Saclay','Diplômes nationaux','Master','METHODES INFORMATIQUES APPLIQUEES A LA GESTION DES ENTREPRISES-MIAGE','Sciences et sciences de lingénieur','Informatique',61,16,45,'91471','Orsay','Essonne','A25','Versailles','R11','Île-de-France','0912408Y','Université Paris-Saclay');
INSERT INTO masters VALUES (142,'Université','CY Cergy Paris Université','Diplômes détablissement','Diplômes détablissement','DIPLOMES DUNIVERSITES EN INFORMATIQUE - BAC+3 A BAC+5','Sciences et sciences de lingénieur','Informatique',0,0,0,'95500','Pontoise','Val-dOise','A25','Versailles','R11','Île-de-France','0952259P','CY Cergy Paris Université');
INSERT INTO masters VALUES (143,'École','Université de technologie de Troyes','Diplômes détablissement','Diplômes détablissement','DIPLOMES DUNIVERSITE EN INFORMATIQUE - BAC+4','Sciences et sciences de lingénieur','Informatique',18,8,10,'10387','Troyes','Aube','A19','Reims','R44','Grand Est','0101060Y','Université de technologie de Troyes');
INSERT INTO masters VALUES (144,'Université','Université Jean Monnet','Diplômes détablissement','Diplômes détablissement','DIPLOMES DUNIVERSITE EN INFORMATIQUE - BAC+4 A BAC+6 ET PLUS','Sciences et sciences de lingénieur','Informatique',0,0,0,'42218','Saint-Étienne','Loire','A10','Lyon','R84','Auvergne-Rhône-Alpes','0421095M','Université Jean Monnet');
INSERT INTO masters VALUES (145,'École','Toulouse INP','Diplômes détablissement','Diplômes détablissement','DIPLOMES DUNIVERSITE EN INFORMATIQUE - BAC+5 A BAC+6 ET PLUS','Sciences et sciences de lingénieur','Informatique',7,2,5,'31555','Toulouse','Haute-Garonne','A16','Toulouse','R76','Occitanie','0311381H','Toulouse INP');
INSERT INTO masters VALUES (146,'École','École nationale supérieure dingénieurs de Caen','Diplômes détablissement','Diplômes détablissement','MASTERES SPECIALISES EN INFORMATIQUE - BAC+5 A BAC+6 ET PLUS','Sciences et sciences de lingénieur','Informatique',49,8,41,'14118','Caen','Calvados','A70','Normandie','R28','Normandie','0141720U','École nationale supérieure dingénieurs de Caen');
INSERT INTO masters VALUES (147,'Université','Université Polytechnique Hauts-de-France','Diplômes nationaux','Master','AUDIOVISUEL, MEDIAS INTERACTIFS NUMERIQUES, JEUX','Sciences et sciences de lingénieur','Informatique',71,17,54,'59606','Valenciennes','Nord','A09','Lille','R32','Hauts-de-France','0597131F','Université Polytechnique Hauts-de-France');
INSERT INTO masters VALUES (148,'Université','Université Grenoble Alpes','Diplômes nationaux','Master','INFORMATIQUE','Sciences et sciences de lingénieur','Informatique',81,14,67,'38421','Saint-Martin-dHères','Isère','A08','Grenoble','R84','Auvergne-Rhône-Alpes','0383546Y','Université Grenoble Alpes');
INSERT INTO masters VALUES (149,'Université','Université Paris-Saclay','Diplômes nationaux','Master','INFORMATIQUE','Sciences et sciences de lingénieur','Informatique',0,0,0,'35051','Cesson-Sévigné','Ille-et-Vilaine','A14','Rennes','R53','Bretagne','0912341A','Université Paris-Saclay');
INSERT INTO masters VALUES (150,'Université','La Rochelle Université','Diplômes nationaux','Master','INFORMATIQUE','Sciences et sciences de lingénieur','Informatique',67,9,58,'17300','La Rochelle','Charente-Maritime','A13','Poitiers','R75','Nouvelle-Aquitaine','0171463Y','La Rochelle Université');
INSERT INTO masters VALUES (151,'Université','Université de Franche-Comté','Diplômes nationaux','Master','INFORMATIQUE','Sciences et sciences de lingénieur','Informatique',152,30,122,'25056','Besançon','Doubs','A03','Besançon','R27','Bourgogne-Franche-Comté','0251215K','Université de Franche-Comté');
INSERT INTO masters VALUES (152,'École','École nationale dingénieurs de Brest','Diplômes nationaux','Master','INFORMATIQUE','Sciences et sciences de lingénieur','Informatique',0,0,0,'29019','Brest','Finistère','A14','Rennes','R53','Bretagne','0290119X','École nationale dingénieurs de Brest');
INSERT INTO masters VALUES (153,'Université','Université Le Havre Normandie','Diplômes nationaux','Master','INFORMATIQUE','Sciences et sciences de lingénieur','Informatique',51,8,43,'76351','Le Havre','Seine-Maritime','A70','Normandie','R28','Normandie','0762762P','Université Le Havre Normandie');
INSERT INTO masters VALUES (154,'Université','Université Paris sciences et lettres','Diplômes nationaux','Master','INFORMATIQUE','Sciences et sciences de lingénieur','Informatique',120,45,75,'75116','Paris 16e','Paris','A01','Paris','R11','Île-de-France','0750736T','Université Paris sciences et lettres');
INSERT INTO masters VALUES (155,'Université','Université Gustave Eiffel','Diplômes nationaux','Master','INFORMATIQUE','Sciences et sciences de lingénieur','Informatique',74,8,66,'77083','Champs-sur-Marne','Seine-et-Marne','A24','Créteil','R11','Île-de-France','0772894C','Université Gustave Eiffel');
INSERT INTO masters VALUES (156,'Université','Université Paris Cité','Diplômes nationaux','Master','INFORMATIQUE','Sciences et sciences de lingénieur','Informatique',123,37,86,'75106','Paris  6e','Paris','A01','Paris','R11','Île-de-France','0755976N','Université Paris Cité');
INSERT INTO masters VALUES (157,'Université','Université de Haute-Alsace','Diplômes nationaux','Master','INFORMATIQUE','Sciences et sciences de lingénieur','Informatique',17,5,12,'68224','Mulhouse','Haut-Rhin','A15','Strasbourg','R44','Grand Est','0681166Y','Université de Haute-Alsace');
INSERT INTO masters VALUES (158,'École','École normale supérieure de Lyon','Diplômes nationaux','Master','INFORMATIQUE','Sciences et sciences de lingénieur','Informatique',34,4,30,'69387','Lyon 7e','Rhône','A10','Lyon','R84','Auvergne-Rhône-Alpes','0694123G','École normale supérieure de Lyon');
INSERT INTO masters VALUES (159,'Université','Le Mans Université','Diplômes nationaux','Master','INFORMATIQUE','Sciences et sciences de lingénieur','Informatique',32,5,27,'72181','Le Mans','Sarthe','A17','Nantes','R52','Pays de la Loire','0720916E','Le Mans Université');
INSERT INTO masters VALUES (160,'Université','Université de Lille','Diplômes nationaux','Master','INFORMATIQUE','Sciences et sciences de lingénieur','Informatique',133,25,108,'59009','Villeneuve-dAscq','Nord','A09','Lille','R32','Hauts-de-France','0597239Y','Université de Lille');
INSERT INTO masters VALUES (161,'Grand établissement','Université de Lorraine','Diplômes nationaux','Master','INFORMATIQUE','Sciences et sciences de lingénieur','Informatique',50,12,38,'54547','Vandœuvre-lès-Nancy','Meurthe-et-Moselle','A12','Nancy-Metz','R44','Grand Est','0542493S','Université de Lorraine');
INSERT INTO masters VALUES (162,'Université','Université Clermont Auvergne','Diplômes nationaux','Master','INFORMATIQUE','Sciences et sciences de lingénieur','Informatique',74,15,59,'63113','Clermont-Ferrand','Puy-de-Dôme','A06','Clermont-Ferrand','R84','Auvergne-Rhône-Alpes','0632084Y','Université Clermont Auvergne');
INSERT INTO masters VALUES (163,'Université','Université de Strasbourg','Diplômes nationaux','Master','INFORMATIQUE','Sciences et sciences de lingénieur','Informatique',98,8,90,'67482','Strasbourg','Bas-Rhin','A15','Strasbourg','R44','Grand Est','0673021V','Université de Strasbourg');
INSERT INTO masters VALUES (164,'Université','Université de La Réunion','Diplômes nationaux','Master','INFORMATIQUE','Sciences et sciences de lingénieur','Informatique',14,1,13,'97411','Saint-Denis','La Réunion','A28','La Réunion','R04','La Réunion','9740478B','Université de La Réunion');
INSERT INTO masters VALUES (165,'Université','Université Paris-Saclay','Diplômes nationaux','Master','INFORMATIQUE','Sciences et sciences de lingénieur','Informatique',22,2,20,'91272','Gif-sur-Yvette','Essonne','A25','Versailles','R11','Île-de-France','0912408Y','Université Paris-Saclay');
INSERT INTO masters VALUES (166,'Université','Université Paris-Saclay','Diplômes nationaux','Master','INFORMATIQUE','Sciences et sciences de lingénieur','Informatique',101,33,68,'91471','Orsay','Essonne','A25','Versailles','R11','Île-de-France','0912408Y','Université Paris-Saclay');
INSERT INTO masters VALUES (167,'Université','Avignon Université','Diplômes nationaux','Master','INFORMATIQUE','Sciences et sciences de lingénieur','Informatique',71,15,56,'84007','Avignon','Vaucluse','A02','Aix-Marseille','R93','Provence-Alpes-Côte dAzur','0840685N','Avignon Université');
INSERT INTO masters VALUES (168,'Université','Avignon Université','Diplômes nationaux','Master','INFORMATIQUE','Sciences et sciences de lingénieur','Informatique',76,13,63,'84007','Avignon','Vaucluse','A02','Aix-Marseille','R93','Provence-Alpes-Côte dAzur','0840685N','Avignon Université');
INSERT INTO masters VALUES (169,'Université','Université de Picardie Jules-Verne','Diplômes nationaux','Master','INFORMATIQUE','Sciences et sciences de lingénieur','Informatique',29,4,25,'80021','Amiens','Somme','A20','Amiens','R32','Hauts-de-France','0801344B','Université de Picardie Jules-Verne');
INSERT INTO masters VALUES (170,'École','École nationale dingénieurs de Brest','Diplômes nationaux','Master','RESEAUX ET TELECOMMUNICATION','Sciences et sciences de lingénieur','Informatique',3,2,1,'29019','Brest','Finistère','A14','Rennes','R53','Bretagne','0290119X','École nationale dingénieurs de Brest');
INSERT INTO masters VALUES (171,'Université','Université Toulouse III - Paul Sabatier','Diplômes nationaux','Master','RESEAUX ET TELECOMMUNICATION','Sciences et sciences de lingénieur','Informatique',34,4,30,'31555','Toulouse','Haute-Garonne','A16','Toulouse','R76','Occitanie','0311384L','Université Toulouse III - Paul Sabatier');
INSERT INTO masters VALUES (172,'Université','Université Polytechnique Hauts-de-France','Diplômes nationaux','Master','RESEAUX ET TELECOMMUNICATION','Sciences et sciences de lingénieur','Informatique',13,1,12,'59392','Maubeuge','Nord','A09','Lille','R32','Hauts-de-France','0597131F','Université Polytechnique Hauts-de-France');
INSERT INTO masters VALUES (173,'Université','Université de Lille','Diplômes nationaux','Master','RESEAUX ET TELECOMMUNICATION','Sciences et sciences de lingénieur','Informatique',26,15,11,'59009','Villeneuve-dAscq','Nord','A09','Lille','R32','Hauts-de-France','0597239Y','Université de Lille');
INSERT INTO masters VALUES (174,'École','Centrale Lille Institut','Diplômes nationaux','Master','RESEAUX ET TELECOMMUNICATION','Sciences et sciences de lingénieur','Informatique',2,1,1,'59009','Villeneuve-dAscq','Nord','A09','Lille','R32','Hauts-de-France','0597139P','Centrale Lille Institut');
INSERT INTO masters VALUES (175,'Université','Université Savoie Mont Blanc','Diplômes nationaux','Master','RESEAUX ET TELECOMMUNICATION','Sciences et sciences de lingénieur','Informatique',39,3,36,'73051','Le Bourget-du-Lac','Savoie','A08','Grenoble','R84','Auvergne-Rhône-Alpes','0730858L','Université Savoie Mont Blanc');
INSERT INTO masters VALUES (176,'Université','Université de Bordeaux','Diplômes nationaux','Master','METHODES INFORMATIQUES APPLIQUEES A LA GESTION DES ENTREPRISES-MIAGE','Sciences et sciences de lingénieur','Informatique',66,11,55,'33522','Talence','Gironde','A04','Bordeaux','R75','Nouvelle-Aquitaine','0333298F','Université de Bordeaux');
INSERT INTO masters VALUES (177,'Université','Université dOrléans','Diplômes nationaux','Master','METHODES INFORMATIQUES APPLIQUEES A LA GESTION DES ENTREPRISES-MIAGE','Sciences et sciences de lingénieur','Informatique',35,9,26,'45234','Orléans','Loiret','A18','Orléans-Tours','R24','Centre-Val de Loire','0450855K','Université dOrléans');
INSERT INTO masters VALUES (178,'Université','Université Grenoble Alpes','Diplômes nationaux','Master','METHODES INFORMATIQUES APPLIQUEES A LA GESTION DES ENTREPRISES-MIAGE','Sciences et sciences de lingénieur','Informatique',40,7,33,'38421','Saint-Martin-dHères','Isère','A08','Grenoble','R84','Auvergne-Rhône-Alpes','0383546Y','Université Grenoble Alpes');
INSERT INTO masters VALUES (179,'Université','Université Grenoble Alpes','Diplômes nationaux','Master','METHODES INFORMATIQUES APPLIQUEES A LA GESTION DES ENTREPRISES-MIAGE','Sciences et sciences de lingénieur','Informatique',48,8,40,'38421','Saint-Martin-dHères','Isère','A08','Grenoble','R84','Auvergne-Rhône-Alpes','0383546Y','Université Grenoble Alpes');
INSERT INTO masters VALUES (180,'Université','Université Côte dAzur','Diplômes nationaux','Master','METHODES INFORMATIQUES APPLIQUEES A LA GESTION DES ENTREPRISES-MIAGE','Sciences et sciences de lingénieur','Informatique',64,15,49,6018,'Biot','Alpes-Maritimes','A23','Nice','R93','Provence-Alpes-Côte dAzur','0062205P','Université Côte dAzur');
INSERT INTO masters VALUES (181,'Université','Université Toulouse Capitole','Diplômes nationaux','Master','METHODES INFORMATIQUES APPLIQUEES A LA GESTION DES ENTREPRISES-MIAGE','Sciences et sciences de lingénieur','Informatique',123,57,66,'31555','Toulouse','Haute-Garonne','A16','Toulouse','R76','Occitanie','0311382J','Université Toulouse Capitole');
INSERT INTO masters VALUES (182,'Université','Université Toulouse III - Paul Sabatier','Diplômes nationaux','Master','METHODES INFORMATIQUES APPLIQUEES A LA GESTION DES ENTREPRISES-MIAGE','Sciences et sciences de lingénieur','Informatique',54,17,37,'31555','Toulouse','Haute-Garonne','A16','Toulouse','R76','Occitanie','0311384L','Université Toulouse III - Paul Sabatier');
INSERT INTO masters VALUES (183,'Université','Université Paris Nanterre','Diplômes nationaux','Master','METHODES INFORMATIQUES APPLIQUEES A LA GESTION DES ENTREPRISES-MIAGE','Sciences et sciences de lingénieur','Informatique',40,12,28,'92050','Nanterre','Hauts-de-Seine','A25','Versailles','R11','Île-de-France','0921204J','Université Paris Nanterre');
INSERT INTO masters VALUES (184,'Université','Université des Antilles','Diplômes nationaux','Master','METHODES INFORMATIQUES APPLIQUEES A LA GESTION DES ENTREPRISES-MIAGE','Sciences et sciences de lingénieur','Informatique',10,1,9,'97120','Pointe-à-Pitre','Guadeloupe','A32','Guadeloupe','R01','Guadeloupe','9710585J','Université des Antilles');
INSERT INTO masters VALUES (185,'Université','Université de Haute-Alsace','Diplômes détablissement','Diplômes détablissement','DIPLOMES DUNIVERSITE EN INFORMATIQUE - BAC A BAC+5','Sciences et sciences de lingénieur','Informatique',52,5,47,'68224','Mulhouse','Haut-Rhin','A15','Strasbourg','R44','Grand Est','0681166Y','Université de Haute-Alsace');
INSERT INTO masters VALUES (186,'Université','Université Sorbonne Paris Nord','Diplômes nationaux','Master','INGENIERIE ET INNOVATION EN IMAGES ET RESEAUX','Sciences et sciences de lingénieur','Informatique',51,28,23,'93079','Villetaneuse','Seine-Saint-Denis','A24','Créteil','R11','Île-de-France','0931238R','Université Sorbonne Paris Nord');
INSERT INTO masters VALUES (187,'Université','CY Cergy Paris Université','Diplômes détablissement','Diplômes détablissement','DIPLOMES DUNIVERSITE EN INFORMATIQUE - BAC+4 A BAC+5','Sciences et sciences de lingénieur','Informatique',23,7,16,'95127','Cergy','Val-dOise','A25','Versailles','R11','Île-de-France','0952259P','CY Cergy Paris Université');
INSERT INTO masters VALUES (188,'Université','Université Paris-Saclay','Diplômes détablissement','Diplômes détablissement','DIPLOMES DUNIVERSITE EN INFORMATIQUE - BAC+5','Sciences et sciences de lingénieur','Informatique',1,0,1,'91471','Orsay','Essonne','A25','Versailles','R11','Île-de-France','0912408Y','Université Paris-Saclay');
INSERT INTO masters VALUES (189,'École','Institut national des sciences appliquées de Lyon','Diplômes détablissement','Diplômes détablissement','MASTERES SPECIALISES EN INFORMATIQUE - BAC+4 A BAC+5','Sciences et sciences de lingénieur','Informatique',13,3,10,'69266','Villeurbanne','Rhône','A10','Lyon','R84','Auvergne-Rhône-Alpes','0690192J','Institut national des sciences appliquées de Lyon');
INSERT INTO masters VALUES (190,'École','Institut national des sciences appliquées de Rouen Normandie','Diplômes nationaux','Master','SCIENCES ET INGENIERIE DES DONNEES','Sciences et sciences de lingénieur','Informatique',0,0,0,'76575','Saint-Étienne-du-Rouvray','Seine-Maritime','A70','Normandie','R28','Normandie','0760165S','Institut national des sciences appliquées de Rouen Normandie');
INSERT INTO masters VALUES (191,'Université','CY Cergy Paris Université','Diplômes nationaux','Master','INFORMATIQUE ET INGENIERIE DES SYSTEMES COMPLEXES','Sciences et sciences de lingénieur','Informatique',32,8,24,'95500','Pontoise','Val-dOise','A25','Versailles','R11','Île-de-France','0952259P','CY Cergy Paris Université');
INSERT INTO masters VALUES (192,'Université','Université Paris Cité','Diplômes nationaux','Master','INFORMATIQUE FONDAMENTALE ET APPLIQUEE','Sciences et sciences de lingénieur','Informatique',106,20,86,'75113','Paris 13e','Paris','A01','Paris','R11','Île-de-France','0755976N','Université Paris Cité');
INSERT INTO masters VALUES (193,'Université','Université Paris sciences et lettres','Diplômes détablissement','Diplômes détablissement','NON DETAILLE','Sciences et sciences de lingénieur','Informatique',58,7,51,'75105','Paris  5e','Paris','A01','Paris','R11','Île-de-France','0753455Y','Université Paris sciences et lettres');
INSERT INTO masters VALUES (194,'École','Centrale Marseille','Diplômes détablissement','Diplômes détablissement','NON DETAILLE','Sciences et sciences de lingénieur','Informatique',16,2,14,'13213','Marseille 13e','Bouches-du-Rhône','A02','Aix-Marseille','R93','Provence-Alpes-Côte dAzur','0133774G','Centrale Marseille');
INSERT INTO masters VALUES (195,'Grand établissement','Bordeaux INP','Diplômes détablissement','Diplômes détablissement','NON DETAILLE','Sciences et sciences de lingénieur','Informatique',8,1,7,'33522','Talence','Gironde','A04','Bordeaux','R75','Nouvelle-Aquitaine','0333232J','Bordeaux INP');
INSERT INTO masters VALUES (196,'Université','Université de Rouen Normandie','Diplômes nationaux','Master','SCIENCES ET INGENIERIE DES DONNEES','Sciences et sciences de lingénieur','Informatique',36,11,25,'76575','Saint-Étienne-du-Rouvray','Seine-Maritime','A70','Normandie','R28','Normandie','0761904G','Université de Rouen Normandie');
INSERT INTO masters VALUES (197,'Université','CY Cergy Paris Université','Diplômes nationaux','Master','INFORMATIQUE ET INGENIERIE DES SYSTEMES COMPLEXES','Sciences et sciences de lingénieur','Informatique',68,16,52,'95500','Pontoise','Val-dOise','A25','Versailles','R11','Île-de-France','0952259P','CY Cergy Paris Université');
INSERT INTO masters VALUES (198,'Université','Université Paris Cité','Diplômes nationaux','Master','INFORMATIQUE FONDAMENTALE ET APPLIQUEE','Sciences et sciences de lingénieur','Informatique',111,22,89,'75113','Paris 13e','Paris','A01','Paris','R11','Île-de-France','0755976N','Université Paris Cité');
INSERT INTO masters VALUES (199,'Université','Université Polytechnique Hauts-de-France','Diplômes nationaux','Master','AUDIOVISUEL, MEDIAS INTERACTIFS NUMERIQUES, JEUX','Sciences et sciences de lingénieur','Informatique',44,12,32,'59606','Valenciennes','Nord','A09','Lille','R32','Hauts-de-France','0597131F','Université Polytechnique Hauts-de-France');
INSERT INTO masters VALUES (200,'Université','Université Jean Monnet','Diplômes nationaux','Master','INFORMATIQUE','Sciences et sciences de lingénieur','Informatique',49,13,36,'42218','Saint-Étienne','Loire','A10','Lyon','R84','Auvergne-Rhône-Alpes','0421095M','Université Jean Monnet');
INSERT INTO masters VALUES (201,'Université','Université Grenoble Alpes','Diplômes nationaux','Master','INFORMATIQUE','Sciences et sciences de lingénieur','Informatique',114,21,93,'38421','Saint-Martin-dHères','Isère','A08','Grenoble','R84','Auvergne-Rhône-Alpes','0383546Y','Université Grenoble Alpes');
INSERT INTO masters VALUES (202,'Université','Université de Tours','Diplômes nationaux','Master','INFORMATIQUE','Sciences et sciences de lingénieur','Informatique',38,10,28,'37261','Tours','Indre-et-Loire','A18','Orléans-Tours','R24','Centre-Val de Loire','0370800U','Université de Tours');
INSERT INTO masters VALUES (203,'École','École normale supérieure de Rennes','Diplômes nationaux','Master','INFORMATIQUE','Sciences et sciences de lingénieur','Informatique',13,0,13,'35047','Bruz','Ille-et-Vilaine','A14','Rennes','R53','Bretagne','0352440M','École normale supérieure de Rennes');
INSERT INTO masters VALUES (204,'Université','Université de Bordeaux','Diplômes nationaux','Master','INFORMATIQUE','Sciences et sciences de lingénieur','Informatique',166,23,143,'33522','Talence','Gironde','A04','Bordeaux','R75','Nouvelle-Aquitaine','0333298F','Université de Bordeaux');
INSERT INTO masters VALUES (205,'Université','Université de Montpellier','Diplômes nationaux','Master','INFORMATIQUE','Sciences et sciences de lingénieur','Informatique',137,46,91,'34172','Montpellier','Hérault','A11','Montpellier','R76','Occitanie','0342490X','Université de Montpellier');
INSERT INTO masters VALUES (206,'Université','Aix-Marseille Université','Diplômes nationaux','Master','INFORMATIQUE','Sciences et sciences de lingénieur','Informatique',37,11,26,'13213','Marseille 13e','Bouches-du-Rhône','A02','Aix-Marseille','R93','Provence-Alpes-Côte dAzur','0134009M','Aix-Marseille Université');
INSERT INTO masters VALUES (207,'Université','Université Toulouse III - Paul Sabatier','Diplômes nationaux','Master','INFORMATIQUE','Sciences et sciences de lingénieur','Informatique',188,39,149,'31555','Toulouse','Haute-Garonne','A16','Toulouse','R76','Occitanie','0311384L','Université Toulouse III - Paul Sabatier');
INSERT INTO masters VALUES (208,'Université','Université Toulouse III - Paul Sabatier','Diplômes nationaux','Master','INFORMATIQUE','Sciences et sciences de lingénieur','Informatique',214,40,174,'31555','Toulouse','Haute-Garonne','A16','Toulouse','R76','Occitanie','0311384L','Université Toulouse III - Paul Sabatier');
INSERT INTO masters VALUES (209,'Université','Université Paris sciences et lettres','Diplômes nationaux','Master','INFORMATIQUE','Sciences et sciences de lingénieur','Informatique',216,77,139,'75116','Paris 16e','Paris','A01','Paris','R11','Île-de-France','0750736T','Université Paris sciences et lettres');
INSERT INTO masters VALUES (210,'Université','Université de Rouen Normandie','Diplômes nationaux','Master','INFORMATIQUE','Sciences et sciences de lingénieur','Informatique',72,19,53,'76575','Saint-Étienne-du-Rouvray','Seine-Maritime','A70','Normandie','R28','Normandie','0761904G','Université de Rouen Normandie');
INSERT INTO masters VALUES (211,'École','École normale supérieure de Lyon','Diplômes nationaux','Master','INFORMATIQUE','Sciences et sciences de lingénieur','Informatique',49,7,42,'69387','Lyon 7e','Rhône','A10','Lyon','R84','Auvergne-Rhône-Alpes','0694123G','École normale supérieure de Lyon');
INSERT INTO masters VALUES (212,'Université','Université Savoie Mont Blanc','Diplômes nationaux','Master','INFORMATIQUE','Sciences et sciences de lingénieur','Informatique',35,2,33,'73051','Le Bourget-du-Lac','Savoie','A08','Grenoble','R84','Auvergne-Rhône-Alpes','0730858L','Université Savoie Mont Blanc');
INSERT INTO masters VALUES (213,'Université','Université Paris sciences et lettres','Diplômes nationaux','Master','INFORMATIQUE','Sciences et sciences de lingénieur','Informatique',24,5,19,'75105','Paris  5e','Paris','A01','Paris','R11','Île-de-France','0753455Y','Université Paris sciences et lettres');
INSERT INTO masters VALUES (214,'Université','Université Paris-Saclay','Diplômes nationaux','Master','INFORMATIQUE','Sciences et sciences de lingénieur','Informatique',0,0,0,'57463','Metz','Moselle','A12','Nancy-Metz','R44','Grand Est','0912341A','Université Paris-Saclay');
INSERT INTO masters VALUES (215,'Grand établissement','Université de Lorraine','Diplômes nationaux','Master','INFORMATIQUE','Sciences et sciences de lingénieur','Informatique',82,15,67,'57463','Metz','Moselle','A12','Nancy-Metz','R44','Grand Est','0542493S','Université de Lorraine');
INSERT INTO masters VALUES (216,'Université','Université de Lille','Diplômes nationaux','Master','INFORMATIQUE','Sciences et sciences de lingénieur','Informatique',116,17,99,'59009','Villeneuve-dAscq','Nord','A09','Lille','R32','Hauts-de-France','0597239Y','Université de Lille');
INSERT INTO masters VALUES (217,'Grand établissement','Université de Lorraine','Diplômes nationaux','Master','INFORMATIQUE','Sciences et sciences de lingénieur','Informatique',46,9,37,'54547','Vandœuvre-lès-Nancy','Meurthe-et-Moselle','A12','Nancy-Metz','R44','Grand Est','0542493S','Université de Lorraine');
INSERT INTO masters VALUES (218,'Université','Université de Reims Champagne-Ardenne','Diplômes nationaux','Master','INFORMATIQUE','Sciences et sciences de lingénieur','Informatique',34,13,21,'51454','Reims','Marne','A19','Reims','R44','Grand Est','0511296G','Université de Reims Champagne-Ardenne');
INSERT INTO masters VALUES (219,'Université','Université du Littoral Côte dOpale','Diplômes nationaux','Master','INFORMATIQUE','Sciences et sciences de lingénieur','Informatique',28,1,27,'62193','Calais','Pas-de-Calais','A09','Lille','R32','Hauts-de-France','0595964M','Université du Littoral Côte dOpale');
INSERT INTO masters VALUES (220,'Université','Université dArtois','Diplômes nationaux','Master','INFORMATIQUE','Sciences et sciences de lingénieur','Informatique',59,11,48,'62498','Lens','Pas-de-Calais','A09','Lille','R32','Hauts-de-France','0623957P','Université dArtois');
INSERT INTO masters VALUES (221,'Université','Université Polytechnique Hauts-de-France','Diplômes nationaux','Master','INFORMATIQUE','Sciences et sciences de lingénieur','Informatique',45,8,37,'59606','Valenciennes','Nord','A09','Lille','R32','Hauts-de-France','0597131F','Université Polytechnique Hauts-de-France');
INSERT INTO masters VALUES (222,'Université','Université de Strasbourg','Diplômes nationaux','Master','INFORMATIQUE','Sciences et sciences de lingénieur','Informatique',102,13,89,'67482','Strasbourg','Bas-Rhin','A15','Strasbourg','R44','Grand Est','0673021V','Université de Strasbourg');
INSERT INTO masters VALUES (223,'Université','Université de Pau et des Pays de lAdour','Diplômes nationaux','Master','INFORMATIQUE','Sciences et sciences de lingénieur','Informatique',42,7,35,'64445','Pau','Pyrénées-Atlantiques','A04','Bordeaux','R75','Nouvelle-Aquitaine','0640251A','Université de Pau et des Pays de lAdour');
INSERT INTO masters VALUES (224,'Université','Université Paris-Est Créteil','Diplômes nationaux','Master','INFORMATIQUE','Sciences et sciences de lingénieur','Informatique',30,6,24,'94028','Créteil','Val-de-Marne','A24','Créteil','R11','Île-de-France','0941111X','Université Paris-Est Créteil');
INSERT INTO masters VALUES (225,'Université','Université des Antilles','Diplômes nationaux','Master','INFORMATIQUE','Sciences et sciences de lingénieur','Informatique',11,1,10,'97120','Pointe-à-Pitre','Guadeloupe','A32','Guadeloupe','R01','Guadeloupe','9710585J','Université des Antilles');
INSERT INTO masters VALUES (226,'Université','Université de Poitiers','Diplômes nationaux','Master','INFORMATIQUE','Sciences et sciences de lingénieur','Informatique',58,12,46,'86194','Poitiers','Vienne','A13','Poitiers','R75','Nouvelle-Aquitaine','0860856N','Université de Poitiers');
INSERT INTO masters VALUES (227,'Université','Université Paris-Saclay','Diplômes nationaux','Master','INFORMATIQUE','Sciences et sciences de lingénieur','Informatique',65,13,52,'91228','Évry-Courcouronnes','Essonne','A25','Versailles','R11','Île-de-France','0912408Y','Université Paris-Saclay');
INSERT INTO masters VALUES (228,'Université','Université Paris-Saclay','Diplômes nationaux','Master','INFORMATIQUE','Sciences et sciences de lingénieur','Informatique',32,12,20,'91228','Évry-Courcouronnes','Essonne','A25','Versailles','R11','Île-de-France','0912408Y','Université Paris-Saclay');
INSERT INTO masters VALUES (229,'École','Université de technologie de Belfort-Montbéliard','Diplômes nationaux','Master','INFORMATIQUE','Sciences et sciences de lingénieur','Informatique',5,1,4,'90094','Sevenans','Territoire de Belfort','A03','Besançon','R27','Bourgogne-Franche-Comté','0900424X','Université de technologie de Belfort-Montbéliard');
INSERT INTO masters VALUES (230,'Université','Université Paris-Saclay','Diplômes nationaux','Master','INFORMATIQUE','Sciences et sciences de lingénieur','Informatique',32,4,28,'91272','Gif-sur-Yvette','Essonne','A25','Versailles','R11','Île-de-France','0912408Y','Université Paris-Saclay');
INSERT INTO masters VALUES (231,'Université','Université de Toulon','Diplômes nationaux','Master','INFORMATIQUE','Sciences et sciences de lingénieur','Informatique',14,0,14,'83062','La Garde','Var','A23','Nice','R93','Provence-Alpes-Côte dAzur','0830766G','Université de Toulon');
INSERT INTO masters VALUES (232,'Université','Université de Picardie Jules-Verne','Diplômes nationaux','Master','INFORMATIQUE','Sciences et sciences de lingénieur','Informatique',5,0,5,'80021','Amiens','Somme','A20','Amiens','R32','Hauts-de-France','0801344B','Université de Picardie Jules-Verne');
INSERT INTO masters VALUES (233,'Université','Université de Bretagne Occidentale','Diplômes nationaux','Master','RESEAUX ET TELECOMMUNICATION','Sciences et sciences de lingénieur','Informatique',62,18,44,'29019','Brest','Finistère','A14','Rennes','R53','Bretagne','0290346U','Université de Bretagne Occidentale');
INSERT INTO masters VALUES (234,'École','Toulouse INP','Diplômes nationaux','Master','RESEAUX ET TELECOMMUNICATION','Sciences et sciences de lingénieur','Informatique',6,4,2,'31555','Toulouse','Haute-Garonne','A16','Toulouse','R76','Occitanie','0311381H','Toulouse INP');
INSERT INTO masters VALUES (235,'Université','Université Polytechnique Hauts-de-France','Diplômes nationaux','Master','RESEAUX ET TELECOMMUNICATION','Sciences et sciences de lingénieur','Informatique',28,4,24,'59606','Valenciennes','Nord','A09','Lille','R32','Hauts-de-France','0597131F','Université Polytechnique Hauts-de-France');
INSERT INTO masters VALUES (236,'Université','Université de Reims Champagne-Ardenne','Diplômes nationaux','Master','RESEAUX ET TELECOMMUNICATION','Sciences et sciences de lingénieur','Informatique',51,8,43,'51454','Reims','Marne','A19','Reims','R44','Grand Est','0511296G','Université de Reims Champagne-Ardenne');
INSERT INTO masters VALUES (237,'Université','Université de Lille','Diplômes nationaux','Master','RESEAUX ET TELECOMMUNICATION','Sciences et sciences de lingénieur','Informatique',28,10,18,'59009','Villeneuve-dAscq','Nord','A09','Lille','R32','Hauts-de-France','0597239Y','Université de Lille');
INSERT INTO masters VALUES (238,'Université','Université de Rennes 1','Diplômes nationaux','Master','METHODES INFORMATIQUES APPLIQUEES A LA GESTION DES ENTREPRISES-MIAGE','Sciences et sciences de lingénieur','Informatique',76,16,60,'35238','Rennes','Ille-et-Vilaine','A14','Rennes','R53','Bretagne','0350936C','Université de Rennes');
INSERT INTO masters VALUES (239,'Université','Aix-Marseille Université','Diplômes nationaux','Master','METHODES INFORMATIQUES APPLIQUEES A LA GESTION DES ENTREPRISES-MIAGE','Sciences et sciences de lingénieur','Informatique',30,7,23,'13001','Aix-en-Provence','Bouches-du-Rhône','A02','Aix-Marseille','R93','Provence-Alpes-Côte dAzur','0134009M','Aix-Marseille Université');
INSERT INTO masters VALUES (240,'Université','Université de Lille','Diplômes nationaux','Master','METHODES INFORMATIQUES APPLIQUEES A LA GESTION DES ENTREPRISES-MIAGE','Sciences et sciences de lingénieur','Informatique',43,9,34,'59009','Villeneuve-dAscq','Nord','A09','Lille','R32','Hauts-de-France','0597239Y','Université de Lille');
INSERT INTO masters VALUES (241,'Université','Université Paris Cité','Diplômes nationaux','Master','METHODES INFORMATIQUES APPLIQUEES A LA GESTION DES ENTREPRISES-MIAGE','Sciences et sciences de lingénieur','Informatique',41,12,29,'75106','Paris  6e','Paris','A01','Paris','R11','Île-de-France','0755976N','Université Paris Cité');
INSERT INTO masters VALUES (242,'Université','Université de la Nouvelle-Calédonie','Diplômes nationaux','Master','METHODES INFORMATIQUES APPLIQUEES A LA GESTION DES ENTREPRISES-MIAGE','Sciences et sciences de lingénieur','Informatique',10,4,6,'98818','Nouméa','Nouvelle-Calédonie','A40','Nouvelle-Calédonie','R00','Collectivités doutre-mer','9830445S','Université de la Nouvelle-Calédonie');
INSERT INTO masters VALUES (243,'Université','Université de Picardie Jules-Verne','Diplômes nationaux','Master','METHODES INFORMATIQUES APPLIQUEES A LA GESTION DES ENTREPRISES-MIAGE','Sciences et sciences de lingénieur','Informatique',134,20,114,'80021','Amiens','Somme','A20','Amiens','R32','Hauts-de-France','0801344B','Université de Picardie Jules-Verne');
INSERT INTO masters VALUES (244,'École','Institut national des sciences appliquées de Lyon','Diplômes détablissement','Diplômes détablissement','MASTERES SPECIALISES EN INFORMATIQUE - BAC+5 A BAC+6 ET PLUS','Sciences et sciences de lingénieur','Informatique',20,6,14,'69266','Villeurbanne','Rhône','A10','Lyon','R84','Auvergne-Rhône-Alpes','0690192J','Institut national des sciences appliquées de Lyon');
INSERT INTO masters VALUES (245,'Université','Université Paris sciences et lettres','Diplômes détablissement','Diplômes détablissement','DIPLOMES DUNIVERSITE EN INFORMATIQUE - BAC+4 A BAC+5','Sciences et sciences de lingénieur','Informatique',38,5,33,'75116','Paris 16e','Paris','A01','Paris','R11','Île-de-France','0750736T','Université Paris sciences et lettres');
INSERT INTO masters VALUES (246,'Université','CY Cergy Paris Université','Diplômes détablissement','Diplômes détablissement','DIPLOMES DUNIVERSITE EN INFORMATIQUE - BAC A BAC+4','Sciences et sciences de lingénieur','Informatique',7,1,6,'78551','Saint-Germain-en-Laye','Yvelines','A25','Versailles','R11','Île-de-France','0952259P','CY Cergy Paris Université');
INSERT INTO masters VALUES (247,'Université','Université de Strasbourg','Diplômes détablissement','Diplômes détablissement','DIPLOMES DUNIVERSITE EN INFORMATIQUE - BAC A BAC+5','Sciences et sciences de lingénieur','Informatique',0,0,0,'67482','Strasbourg','Bas-Rhin','A15','Strasbourg','R44','Grand Est','0673021V','Université de Strasbourg');
